# objectives:
# 1. learn how to create tools in langgraph
# 2. how to create a react agent in langgraph
# 3. work with the types of messages such as tool messages
# 4. test out robustness of our graph

from typing import Annotated, Sequence, TypedDict
from dotenv import load_dotenv
from langchain_core.messages import AIMessage, BaseMessage, HumanMessage, SystemMessage, ToolMessage
from langchain_openai import ChatOpenAI
from langchain_core.tools import tool
from langgraph.graph.message import add_messages
from langgraph.graph import StateGraph, START, END
from langgraph.prebuilt import ToolNode

load_dotenv()

class AgentState(TypedDict):
    # add_message is a reducer function 
    # sequence of messages support list, tuple of different message types(human, system, tool)
    messages : Annotated[Sequence[BaseMessage], add_messages]

@tool
def add(a: int, b: int) -> int:
    """Add two numbers together."""
    return a + b

tools = [add]
model = ChatOpenAI(model= "gpt-4o").bind_tools(tools)

def model_call(state:AgentState) -> AgentState:
    system_prompt = SystemMessage(content="You are my AI assistant, please answer my query")

    response = model.invoke([system_prompt] + state["messages"])
    return {"messages" : [response]}  # reducer function appends the new message to the existing messages in the state

def should_continue(state:AgentState):
    messages = state["messages"]
    last_message = messages[-1]

    if isinstance(last_message, AIMessage) and last_message.tool_calls:
        return "continue"

    return "end"
    
graph = StateGraph(AgentState)

graph.add_node("our_agent", model_call)

tool_node = ToolNode(tools=tools)
graph.add_node("tools", tool_node)

graph.set_entry_point("our_agent")

graph.add_conditional_edges(
    "our_agent",
    should_continue,
    {
        "continue": "tools",
        "end": END
    }
)

# after the tool is called, we want to go back to our agent to process the tool response and generate a final answer for the user
# loop between our agent and the tool until we get a final answer for the user
graph.add_edge("tools", "our_agent")
agent = graph.compile()

agent.invoke({"messages": [HumanMessage(content="What is 2 + 3?")]})



# NOTE:
# Reasoning is hidden inside the model -> Reason
# Tool call generated by the model -> Action
# Tool result returned to the model -> Observation
# Model reasons again using the observation -> Reason again